services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass134
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  postgres:
    image: postgres:18
    container_name: postgres18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apuestas_deportivas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./infrastructure/persistence/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d apuestas_deportivas"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: apuestas_app
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://root:pass134@mongodb:27017/
      POSTGRES_URI: postgresql://postgres:postgres@postgres:5432/apuestas_deportivas
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_started

volumes:
  mongodb_data:
  postgres_data:
